### PR TITLE
Delete unused methods breaking Jackson serialization of dbutilsModule

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
Tests are showing exceptions when trying to serialize dbutilsModule via Jackson

https://teamcity.labkey.org/buildConfiguration/LabKey_Trunk_Premium_Ehr_WnprcEhrPostgres/1515011?expandedTest=build%3A%28id%3A1515011%29%2Cid%3A1973

https://teamcity.labkey.org/repository/download/LabKey_Trunk_Premium_Ehr_WnprcEhrPostgres/1515011:id/WNPRC_PurchasingTest.tar.gz!/202108202340WNPRC_PurchasingTest%23startupErrors_0.html

#### Changes
* Delete unimplemented methods and the unused code that calls them

### CODE REVIEW

**Comment by labkey-adam** [comment]
Looks like `PrivateFileUtil.java` calls `getPrivateContainer()`

**Review by labkey-adam — CHANGES_REQUESTED** [review]
Need to fix build break

**Comment by labkey-jeckels** [comment]
I had deleted the files locally but missed them in my commit and push

**Review by labkey-adam — APPROVED** [review]
Code changes look good. Some test failures, but perhaps pre-existing.

**Pull request merged**
