### PR TITLE
Item 9093 : Allow purchase admins to add a reason for rejecting the purchasing request

### PR DESCRIPTION
**Pull request by labkey-bpatel**
#### Rationale
Allow purchase admins to add a reason for rejecting the purchasing request so that the requesters have some idea of why their purchase request was rejected.

#### Changes
* Update data entry form to display a new text field when 'Request Rejected' status is selected.
* Handle saving of the reason for rejection.
* Update email notification to include reason for rejection.

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@labkey-bpatel am I missed where the rejectReason value gets stored? Is there a new column being added somewhere?

**Comment by labkey-bpatel** [comment]
@labkey-jeckels - rejectReason is an extensible column, i've added that upon folder creation. However, since WNPRC already will have folder created on their test server, I'll be updating the WNPRC Purchasing setup doc.

**Review by labkey-jeckels — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
OK! Found it in WNPRC_Purchasing/src/org/labkey/wnprc_purchasing/WNPRC_PurchasingManager.java

Are you meaning to target the other feature branch? If so, very good

**Comment by labkey-bpatel** [comment]
Yup, targeting the other fb, i created this one off of it so that its easier to code review.

**Pull request merged**
